- name: Install xorg-xinit
  pacman:
    name: xorg-xinit
    state: present
  become: true
  
- name: Link xorg configuration files
  file:
    src="{{ansible_env.HOME}}/.config/dotfiles/ansible-playbooks/roles/front-end/files/{{ item }}"
    dest="{{ansible_env.HOME}}/{{ item }}"
    state=link
    force=yes
  with_items:
    - .xserverrc
    - .xinitrc
    - .zprofile
