- name: Install Xorg packages
  pacaur:
    name: xorg-server,xf86-video-fbdev,xf86-input-libinput,xorg-xinput,xorg-xprop,mesa,xorg-xinit
    state: present
  become: true

- name: Install i3 packages
  pacaur:
    name: i3-wm,i3blocks,i3lock,i3status,dmenu,xautolock,lxappearance,compton
    state: present
  become: true

- name: X startup tweaking (startx)
  lineinfile:
    path: /usr/bin/startx
    regexp: '^defaultserverargs='
    line: 'defaultserverargs="-deferglyphs 16"'
  become: true

- name: Create i3 config dir
  file:
    path: "{{ configs_path }}/i3"
    state: directory
  register: create-i3-dir

- debug: var=create-i3-dir

- name: Symlink i3 configuration file
  file:
    src: "{{ roles_path }}/font-end/files/i3_config"
    dest: "{{ configs_path }}/i3/config"
    state: link
    force: yes

- name: Create i3-status config dir
  file:
    path: "{{ configs_path }}/i3status"
    state: directory

- name: Symlink i3status configuration file
  file:
    src: "{{ roles_path }}/front-end/files/i3status_config"
    dest: "{{ configs_path }}/i3status/config"
    state: link
    force: yes

- name: Symlink xorg configuration files
  file:
    src: "{{ roles_path }}/front-end/files/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    state: link
    force: yes
  with_items:
    - .xserverrc
    - .xinitrc
    - .zprofile

- name: Install solarized versions of Numix GTK2 and GTK3 theme
  pacaur:
    name: gtk-theme-numix-solarized
    state: present
  become: true
