- name: Clone cower
  git:
    repo: 'https://aur.archlinux.org/cower.git'
    dest: "{{ configs_path }}/cower"

- name: Compile cower
  command: makepkg --noconfirm -mfs arg1
  args:
    chdir: "{{ configs_path }}/cower"
  register: cower_makepkg_result

- shell: ls -1 {{ configs_path | quote }}/cower | grep pkg.tar
  register: compiled_cower

- name: Install cower
  when: cower_makepkg_result | changed
  shell: >
    pacman --noconfirm --noprogressbar --needed -U {{ compiled_cower.stdout | quote }}
    chdir="{{ configs_path }}/cower"
  register: cower_install_result
  become: true

- debug: var=cower_install_result

- name: Install cower
  command: makepkg -si --noconfirm arg1
  args:
    chdir: "{{ configs_path }}/cower"
  become: true
  become_user: "{{ ansible_env.USER }}"

- name: Clone pacaur
  git:
    repo: 'https://aur.archlinux.org/pacaur.git'
    dest: "{{ configs_path }}/pacaur"
    
- name: Install pacaur
  command: makepkg -si arg1
  args:
    chdir: "{{ configs_path }}/pacaur"
  become: true
  become_user: "{{ ansible_env.USER }}"
