- name: Clone cower
  git:
    repo: 'https://aur.archlinux.org/cower.git'
    dest: "{{ configs_path }}/cower"

- name: Install cower
  command: makepkg -si arg1
  args:
    chdir: "{{ configs_path }}/cower"
  become: true
  become_user: "{{ ansible_env.USER }}"

- name: Clone pacaur
  git:
    repo: 'https://aur.archlinux.org/pacaur.git'
    dest: "{{ configs_path }}/pacaur"
    
- name: Install pacaur
  command: makepkg -si arg1
  args:
    chdir: "{{ configs_path }}/pacaur"
  become: true
  become_user: "{{ ansible_env.USER }}"
