- name: Run the equivalent of "pacaur -Syu"
  pacman:
    update_cache: yes
    upgrade: yes
  become: true
  register: system_update
  
- debug: var=system_update

- name: Install zsh and zsh-completions
  pacaur:
    name: zsh,zsh-completions
    state: present
  become: true
  register: install_zsh_deps

- debug: var=install_zsh_deps

- name: Install openssh-askpass
  pacaur:
    name: openssh-askpass
    state: present
  become: true
  register: install_openssh_askpasss

- debug: var=install_openssh_askpasss

- name: Copy bashrc to zshrc
  copy:
    src="{{ ansible_env.HOME }}/.bashrc"
    dest="{{ ansible_env.HOME }}/.zshrc"

- name: Copy bash_profile to zprofile
  copy:
    src="{{ ansible_env.HOME }}/.bash_profile"
    dest="{{ ansible_env.HOME }}/.zprofile"

- name: Clone antigen repo
  git:
    repo: 'https://github.com/zsh-users/antigen.git'
    dest: "{{ configs_path }}/antigen"
    version: master

- name: Symlink .zshrc
  file:
    src="{{ roles_path }}/shell/files/.zshrc"
    dest="{{ ansible_env.HOME }}/.zshrc"
    state=link
    force=yes

- name: Set zsh as default shell
  user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh
  become: yes
