- name: Run the equivalent of "pacaur -Syu"
  pacman:
    update_cache: yes
    upgrade: yes
  become: true
  register: system_update
  
- debug: var=system_update

- name: Install zsh and zsh-completions
  pacaur:
    name: zsh,zsh-completions
    state: present
  become: true
  register: install_zsh_deps

- debug: var=install_zsh_deps

- name: Install openssh-askpass
  pacaur:
    name: openssh-askpass
    state: present
  become: true
  register: install_openssh_askpasss

- debug: var=install_openssh_askpasss

- name: Clone antigen repo
  git:
    repo: 'https://github.com/zsh-users/antigen.git'
    dest: "{{ configs_path }}/antigen"
    version: master

- name: Remove .zshrc
  file:
    path: "{{ ansible_env.HOME }}/.zshrc"
    state: absent

- name: Symlink .zshrc
  file:
    src: "{{ roles_path }}/shell/files/.zshrc"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    state: hard
    force: yes

- name: Set correct permissions to .zshrc
  file:
    path: "{{ ansible_env.HOME }}/.zshrc"
    state: touch
    mode: "u=rw,g=r,o=r"

- name: Set zsh as default shell
  user:
    name: "{{ ansible_env.USER }}"
    shell: /bin/zsh
  become: yes
