- name: Install Xorg packages
  pacaur:
    name: xorg-server,xf86-video-fbdev,xf86-input-libinput,xorg-xinput,xorg-xprop,mesa,xorg-xinit,xorg-xkill,xorg-xev,xorg-xbacklight
    state: present
  become: true

- name: Install i3 packages
  pacaur:
    name: i3-wm,i3blocks,i3lock,i3status,i3-scrot,dmenu
    state: present
  become: true

- name: Install additional packages
  pacaur:
    name: xautolock,lxappearance,compton,imagemagick,libnotify,dunst,rofi
    state: present
  become: true

- name: Install fonts packages
  pacaur:
    name: ttf-dejavu,ttf-liberation,nerd-fonts-complete,powerline-fonts
    state: present
  become: true

- name: X startup tweaking (startx)
  lineinfile:
    path: /usr/bin/startx
    regexp: '^defaultserverargs='
    line: 'defaultserverargs="-deferglyphs 16"'
  become: true

- name: Create i3 config dir
  file:
    path: "{{ configs_path }}/i3"
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: Symlink i3 configuration file
  file:
    src: "{{ roles_path }}/front_end/files/config/i3_config"
    dest: "{{ configs_path }}/i3/config"
    state: hard
    force: yes

- name: Set correct permissions to i3 configuration file
  file:
    path: "{{ configs_path }}/i3/config"
    state: touch
    mode: "u=rw,g=r,o=r"

- name: Create i3blocks config dir
  file:
    path: "{{ configs_path }}/i3blocks"
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: Symlink i3blocks configuration file
  file:
    src: "{{ roles_path }}/front_end/files/config/i3blocks.conf"
    dest: "{{ configs_path }}/i3blocks/config"
    state: hard
    force: yes

- name: Set correct permissions to i3blocks configuration file
  file:
    path: "{{ configs_path }}/i3blocks/config"
    state: touch
    mode: "u=rw,g=r,o=r"

- name: Symlink xorg configuration files
  file:
    src: "{{ roles_path }}/front_end/files/config/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    state: hard
    force: yes
  with_items:
    - .xserverrc
    - .xinitrc
    - .zprofile

- name: Set correct permissiones to xorg configuration files
  file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: touch
    mode: "u=rw,g=r,o=r"
  with_items:
    - .xserverrc
    - .xinitrc
    - .zprofile

- name: Create bin dir
  file:
    path: "{{ ansible_env.HOME }}/bin"
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: Symlink scripts
  file:
    src: "{{ roles_path }}/front_end/files/scripts/{{ item }}"
    dest: "{{ ansible_env.HOME }}/bin/{{ item }}"
    state: hard
    force: yes
  with_items:
    - i3exit
    - blurlock
    - dmenu_recency

- name: Set correct permissions to scripts
  file:
    path: "{{ ansible_env.HOME }}/bin/{{ item }}"
    state: touch
    mode: "u=wxr,g=rx,o=rx"
  with_items:
    - i3exit
    - blurlock
    - dmenu_recency

- name: Install solarized versions of Numix GTK2 and GTK3 theme
  pacaur:
    name: gtk-theme-numix-solarized
    state: present
  become: true
