- name: Install Xorg packages
  pacaur:
    name: xorg-server,xf86-video-fbdev,xf86-input-libinput,xorg-xinput,xorg-xprop,mesa,xorg-xinit
    state: present
  become: true

- name: Install i3 packages
  pacaur:
    name: i3-wm,i3blocks,i3lock,i3status,dmenu,xautolock,lxappearance,compton,scrot,imagemagick
    state: present
  become: true

- name: X startup tweaking (startx)
  lineinfile:
    path: /usr/bin/startx
    regexp: '^defaultserverargs='
    line: 'defaultserverargs="-deferglyphs 16"'
  become: true

- name: Create i3 config dir
  file:
    path: "{{ configs_path }}/i3"
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: Symlink i3 configuration file
  file:
    src: "{{ roles_path }}/front_end/files/config/i3_config"
    dest: "{{ configs_path }}/i3/config"
    state: link
    force: yes
    mode: "u=rw,g=r,o=r"

- name: Create i3status config dir
  file:
    path: "{{ configs_path }}/i3status"
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: Symlink i3status configuration file
  file:
    src: "{{ roles_path }}/front_end/files/config/i3status_config"
    dest: "{{ configs_path }}/i3status/config"
    state: link
    force: yes
    mode: "u=rw,g=r,o=r"

- name: Symlink xorg configuration files
  file:
    src: "{{ roles_path }}/front_end/files/config/{{ item }}"
    dest: "{{ ansible_env.HOME }}/{{ item }}"
    state: link
    force: yes
    mode: "u=rw,g=r,o=r"
  with_items:
    - .xserverrc
    - .xinitrc
    - .zprofile

- name: Symlink scripts
  file:
    src: "{{ roles_path }}/front_end/files/scripts/{{ item }}"
    dest: "/usr/bin/{{ item }}"
    state: link
    force: yes
    owner: root
    group: root
    mode: "u=wxr,g=rx,o=rx"
  with_items:
    - i3exit
    - blurlock
  become: true

- name: Install solarized versions of Numix GTK2 and GTK3 theme
  pacaur:
    name: gtk-theme-numix-solarized
    state: present
  become: true
