export CASSANDRA_SERVICE_HOST=172.17.0.2
export CI_CLIENT_USER_ID=test
export CI_CLIENT_ALIAS=test
export CI_CLIENT_SECRET=test
export CASSANDRA_AUTOINIT=true
export KAFKA_BROKER_SERVICE_HOST=172.18.0.3
