- name: Install awesome-terminal-fonts-patched
  become: true
  pacaur: name=awesome-terminal-fonts-patched
  
- name: Install rxvt-unicode-cvs-patched-wideglyphs
  become: true
  pacaur: name=rxvt-unicode-cvs-patched-wideglyphs

- name: Install wget
  become: true
  become_user: "{{ansible_env.USER}}"
  pacaur: name=wget
