- name: Install awesome-terminal-fonts-patched
  become: true
  pacaur: name=awesome-terminal-fonts-patched

- name: Install wget
  become: true
  become_user: "{{ansible_env.USER}}"
  pacaur: name=wget
